ボウリングのスコア計算プログラムオブジェクト指向版
napple29/ruby-practices pull request #6
Opened 2021-10-20 06:40 UTC by napple29

2021-10-25 01:35 UTC, u1tnk requested changes

2021-10-25 01:35 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +class Frame < Shot
ここはちょっとおかしいですね。
継承関係の定番説明だと 動物の一種類が人間の場合に   `人間 < 動物` となります。
この前提で言うと FrameがShotの一種類のように見えますがそうでは無いはずなので。

適切な関係としては Frameのデータとして Shotを持っているという状態と思います。

2021-10-25 01:35 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  def frames
これは frame複数に関わるメソッドなので、Frameクラスに実装するならクラスメソッドが良いと思います。
また framesという変数名は慣習的に `Frameオブジェクトのインスタンスの配列`を連想します。

変数名と格納されている中身を一致させるようにしましょう

2021-10-28 13:48 UTC, u1tnk requested changes

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  def self.devide_frames(all_shots)
devideではなくdivide でしょうか 🤔 

プログラムでスペルミスは割と重要なので気をつけましょう。
記憶が怪しいときは必ず辞書で確認すると良いですね。

余談ですが、データベースのテーブル名など、変更が難しいところでやらかすと、ミスに気づいても誰も修正する事ができずに何年も使われていたりもします 😰

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    @first_shot = Shot.new(first_mark).point
せっかく自作のオブジェクトをnewしているのでそのまま持っておきましょう。
インスタンスで持っておけばpointが必要なときに変換すれば良いですし、他に何かあったときにも使えるかもしれないので柔軟性が上がります。
情報量は Shotオブジェクト > 数値 なので。

また、変数名も first_shotなのでshotインスタンスが入っている事を期待しますので数値が入っていると分かりづらいですね。

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  def self.devide_frames(all_shots)
frameごとのshotの分割をクラスメソッドにしているのは良いですね 👍

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    all_shots.split(',').each do |mark|
all_shotsという名前なのに入っているのが入力そのままなのは良くないですね。
Shotクラスがある以上 xxx_shotsという名前だと Shotオブジェクトの配列を期待します。
また、Shot.newで `mark`という語彙を使っているので中身はmarkの方が近いですね。
とはいえ `all_marks`もmarkの配列っぽいので…
最初から`all_marks = ARGV[0].split(',')` とすると良さそう。

重要なのは 変数名と中身を一致させる事ですね。メソッドやクラス名でも同じです。(オブジェクト指向というかプログラム全体で重要)

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +      score = Shot.new(mark).point
pointとscoreという語彙がどう違うのかが気になりますね。同じなら合わせるべきです。
また、前述しましたが、この時点でオブジェクト化しているのでpointで数値に戻すのはもったいないです。
そのまま持っていて、Frame.newに渡してしまえば良いですね。

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  def smaller_second_to_last
これは名前が分かりづらいですね。処理内容は `!last_frame?` で代替できそうなので、良い名前が付けば

```
def xxxxx
  !last_frame?
end
```

とすれば良いですし、良い名前が無ければそのまま `!last_frame?`を使えば良いと思います。

あとはbooleanを返すときはlast_frame?と同様に`?`を付けましょう。

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    next_frame.instance_variable_get('@first_shot')
instance_variable_getは通常使わないです。

@first_shotを取得したければ `attr_reader`を使って取れるようにしましょう。

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/game.rb
> +      frame.calc_score(@frames[index.succ], @frames[index.succ.succ])
[細かい話]
単純に +1じゃなくて `succ`を見つけたのは良いと思いますが `next`の方が一般的かなと思いました。

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/game.rb
> +  attr_reader :all_shots, :frames
Gameの外側から参照される事は無いはずなので、 `attr_reader`は必要ありません。

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/game.rb
> +    frames = Frame.devide_frames(all_shots)
ここも名前が実際と違うし、 `frames`と `@frames`で違うものが入っているのは混乱します。

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    if next_frame_second_shot(next_frame).zero? && smaller_second_to_last
next_frame_second_shotとかはメソッドが細かすぎますね。
instance_variable_getを使わなくなればメソッド不要になると思います。

2021-10-28 13:48 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    if next_frame_second_shot(next_frame).zero? && smaller_second_to_last
この分岐はnext_frameがstrikeのときに来ると思うのですが、if文を見た感じだとガーターのときに来てしまいそうです。正しいでしょうか？(debugまではしてないので自信無し)

あとは `strike?`メソッドもせっかく作っているので使うと良いと思います。

2021-10-29 04:59 UTC, haruna-tsujita commented on 07.bowling_object/frame.rb
> +      score = Shot.new(mark).point
この部分、修正しようと試みたのですが、frame.rb 31行めの.point（今は.scoreに変更）をなくしてしまうと、game.rb 9行めの@framesの中身が
```rb
#<Frame:0x00007fbc878704d8
  @first_shot=
   #<Shot:0x00007fbc87870460 @mark=#<Shot:0x00007fbc87870cf8 @mark="6">>,
  @index=0,
  @second_shot=
   #<Shot:0x00007fbc87870410 @mark=#<Shot:0x00007fbc87870c08 @mark="3">>,
  @third_shot=#<Shot:0x00007fbc878703c0 @mark=nil>>,
…
```
と、@markが二重になってしまったので数値に変換したままにしています。

2021-10-29 12:41 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +      score = Shot.new(mark).point
それは、ここを修正してそのままにした場合の話なので、
ここをShot.newにしてFrameに渡すのであればFrame側はそのまま保存すれば大丈夫だと思います。

2021-10-29 13:01 UTC, u1tnk requested changes
だいぶ綺麗になりましたね。
あとは divide_framesのところが修正できたら完璧です！

2021-10-29 13:01 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    [@first_shot.score, @second_shot.score].sum == 10
これは `strike?` の判定後に呼ばれる前提の処理になっているので、この内部に  `!strike?`であることを確認もしないといけないですね。

2021-10-29 13:01 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    if next_frame.second_shot == strike?
これは `next_frame.strike?`では無いでしょうか？

2021-10-29 13:01 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    frames = []
ここも frames配列なので frameオブジェクトが入っていて欲しい！

という事で、
framesは Frameオブジェクトの配列にしてしまいましょう。
frame変数は shotsにして、Shotオブジェクトのままにしましょう。

frameをクリアするところで shotsをFrame.newに入れればFrameができます。
indexもカウンタを作ればここで入れられますね。

そうするとGameでは

` @frames = Frame.divide_frames(all_marks)`

だけで良くなりますね。

2021-11-01 08:19 UTC, u1tnk requested changes

2021-11-01 08:19 UTC, u1tnk commented on 07.bowling_object/game.rb
> +    # @frames = divide_frames.map.with_index do |frame, index|
コメントアウトしたところは削除しましょう。

2021-11-01 08:19 UTC, u1tnk commented on 07.bowling_object/game.rb
> +    @frames = Frame.divide_frames(all_marks)
これだと中身が `@frames`なのに Frameオブジェクトでは無いのは同じですね。
前述した divide_frames内でFrame.newしては？というのはここがズレている事で指摘しているので、

他の案として、
いったん この変数をframeごとに分割したShotオブジェクトだよという名前に変更して、その後でFrameオブジェクトに変更して `@frames` に代入するというパターンでも良いです 🙆‍♀️

2021-11-01 08:19 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +          frames << shots.dup
このタイミングでFrame.newできるはずだと思います。
indexで悩むと思うのですが、ヒントとしてはeach_with_index  のものは使えないので、自前で変数作って制御すれば…というあたりです 💪 

あと、 last frameのif文の中もFrameオブジェクトにしないといけないので注意です。

2021-11-01 08:19 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    all_marks.each_with_index do |mark|
結果として index使わなかったと思うのですが、それなら eachのままにしないといけませんね。

2021-11-02 11:56 UTC, u1tnk requested changes

2021-11-02 11:56 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +        frames.last.second_shot.mark = shot
Frame.newしてから後で変更するわけですね。
ちょっと強引ですが、そこは良いとしてmarkにshotを代入しているのは良く無いですね。
というか`frames.last.second_shot = shot` で良さそうです。

2021-11-02 11:56 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    @first_shot = Shot.new(first_mark)
divide_framesで Shot.newしているので、ここでは first_shotという変数名にしてそのまま代入すれば良いと思います。

2021-11-02 11:56 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    index = -1 # インデックスを0から開始したいため
やはり `-1`があるとちょっとびっくりしてしまいますね。
なので、コメントでフォローされてるのは良いです 👍 

単純に 
```
          index += 1
          frames << Frame.new(index, *shots)
```
の順番を
```
          frames << Frame.new(index, *shots)
          index += 1
```

にすれば 0で良いかと思います。

2021-11-02 11:56 UTC, u1tnk commented on 07.bowling_object/shot.rb
> +    mark.mark == 'X' ? 10 : mark.mark.to_i
辻褄を合わせたのは分かりますが、これはおかしいですね。
前述の指摘と合わせれば `mark.mark`→ `mark`にできると思いますよ 💪

2021-11-04 11:54 UTC, u1tnk approved these changes
二点ほど修正必要な指摘はしてますが、修正内容は明確なのでOKとします！
後で修正しておいてください。

2021-11-04 11:54 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    last_frame = []
だいぶ細かくて、ローカル変数だし、もう良いかなってレベルなんですが、
frameという名前でshotsが入ってるのは今までずっと修正してもらってた事なので修正お願いします 🙏 
`last_frame_shots`で良いと思います。

2021-11-04 11:54 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    [@first_shot.score, @second_shot.score].sum == 10
@napple29 
こちらの指摘は見逃してると思います。

2021-11-04 11:54 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    [@first_shot.score, @second_shot&.score || 0, @third_shot&.score || 0].sum
全然修正する必要無いですが、小ネタとしては以下のようにも書けますよ。

```
[@first_shot.score, @second_shot&.score, @third_shot&.score].sum { _1.to_i }
```

```
[@first_shot.score, @second_shot&.score, @third_shot&.score].compact.sum
```

2021-11-04 11:54 UTC, u1tnk commented on 07.bowling_object/game.rb
> +    @frames = Frame.divide_frames(all_marks)
これは解決済みですね。

2021-11-05 12:27 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    [@first_shot.score, @second_shot.score].sum == 10 && !strike?
👍

2021-11-05 12:27 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    [@first_shot.score, @second_shot&.score, @third_shot&.score].compact.sum
👍

2021-11-05 12:27 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +        last_frame_shots << shot
👍

2021-11-06 05:07 UTC, merged